intueriPLM/PLM/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView

from website import Views

urlpatterns = patterns('',

    url(r'^login/$', TemplateView.as_view(template_name="login.html"), name='login'),
)

intueriPLM/intueriPLM/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.views.generic import TemplateView

urlpatterns = patterns('',

    url(r'^admin/', include(admin.site.urls)),
    url(r'^foundation/', include('foundation.urls')),
    url(r'^', include('website.urls', namespace="website")),
    url(r'^PLM/', include('PLM.urls', namespace="PLM")),
)

intueriPLM/website/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView

from website import Views

urlpatterns = patterns('',

    url(r'^$', TemplateView.as_view(template_name="index.html"), name='index'),
    url(r'^pricing/$', TemplateView.as_view(template_name="pricing.html"), name='pricing'),
    url(r'^contactus/$', TemplateView.as_view(template_name="contactus.html"), name='contactus'),
    url(r'^aboutus/$', TemplateView.as_view(template_name="aboutus.html"), name='aboutus'),
)

intueriPLM/polls/models.py
from django.db import models

# Create your models here.

intueriPLM/polls/views.py
from django.shortcuts import render

# Create your views here.

intueriPLM/PLM/templates/PLM_base.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans "Intueri" %}{% endblock %}
{% block base_body %}
  {% block navigation %}
    <div class="row">
        <div class="large-3 columns">
          <h1><a href="{% url 'website:index' %}">
            <img src="http://placehold.it/400x100&text=Logo">
          </a></h1>
        </div>
        <div class="large-9 columns">
          <ul class="button-group right">
            <li><a href="{% url 'PLM:login' %}" class="button">bleh</a></li>
          </ul>
        </div>
      </div>
  {% endblock %}

  {% block content %}
        
  {% endblock %}

  {% block footer %}
    {% include "_footer.html" %}
  {% endblock %}

{% endblock %}

intueriPLM/templates/base.html
{% load staticfiles %}
<!doctype html>
<html class="no-js" lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% block meta %}{% endblock meta %}
    {% block base_title %}
    <title>{% block title %}Foundation 5.5.0{% endblock title %}</title>
    {% endblock base_title %}

    {# Base Foundation CSS #}
    {% block foundation_css %}
    <link href="{% static "foundation/css/normalize.css" %}" rel="stylesheet"/>
    <link href="{% static "foundation/css/foundation.css" %}" rel="stylesheet"/>
    {% endblock foundation_css %}  
    
    {# Custom CSS #}
    <link rel="stylesheet" type="text/css" href="{% static "base/js/slick/slick.css" %}"/>
    <link rel="stylesheet" type="text/css" href="{% static "base/js/slick/slick-theme.css" %}"/>
    {% block css %}{% endblock css %}

    {# Override if you need another version of modernizr #}
    {% block foundation_modernizer %}
    <script src="{% static "foundation/js/vendor/modernizr.js" %}"></script>
    {% endblock foundation_modernizer %}

    {# Custom head JS #}
    {% block head_js %}{% endblock head_js %}
</head>
<body {% block body_attr %}{% endblock body_attr %}>

    {# Override if you need another version of jQuery #}
    {% block foundation_jquery %}
    <script src="{% static "foundation/js/vendor/jquery.js" %}"></script>
    {% endblock foundation_jquery %}

    {# Foundation JS #}
    {% block foundation_js %}
    <script src="{% static "foundation/js/foundation.min.js" %}"></script>
    {% endblock foundation_js %}

    {# Custom JS #}
    {% block body_js %}
    <script type="text/javascript" src="{% static "base/js/slick/slick.min.js" %}"></script>
    {% endblock body_js %}

    {# Main content goes here #}
    {% block base_body %}{% endblock base_body %}

    {# Init Foundation #}
    {% block foundation_js_init %}
    <script>
    $(document).foundation();
    </script>
    {% endblock foundation_js_init %}

</body>
</html>

intueriPLM/website/templates/_footer.html
{% load i18n %}
<footer class="row">
<div class="large-12 columns">
  <hr/>
  <div class="row">
    <div class="small-6 columns">
      <ul class="inline-list">
        <li class="icon icon-facebook">
          <a href="#">
          </a>
        </li>
        <li class="icon icon-twitter">
          <a href="#">
          </a>
        </li>
        <li class="icon icon-instagram">
          <a href="#">
          </a>
        </li>
      </ul>
    </div>
    <div class="small-6 columns">
      <div class="right row">
        <div class="small-8 medium-8 columns">
        <input type="email">
      </div>
      <div class="small-4 medium-4 columns">
        <input type="submit" class="postfix button small" value="Subscribe">
      </div>
      </div>
    </div>
  </div>
</div>
</footer>

intueriPLM/website/templates/aboutus.html
{% extends "site_base.html" %}
{% load i18n %}
{% load staticfiles %}

{% block title %}{% trans "Intueri" %}{% endblock %}
{% block content %}
<script>
$(".top-bar-section ul li:nth-child(3) a").addClass("active");
</script>

<div class="row">
	<div class="large-12 columns main-content-top">
		<div class="row">
			<h2>About Us</h2>
		</div>
	</div>
</div>

<div class="main-content">
	<div class="row">
		<div class="large-12 columns">
			<h2>Our Team</h2>
		</div>
	</div>

	<div class="row smallpadding">
		<div class="medium-5 columns">
			<img class="center" src="{% static "website/media/emily.jpg" %}">
		</div>
		<div class="medium-7 columns ">
			<div class="large-12 columns smallpadding">
				<h4 class="text-center column">Emily</h4>
				<p class="text-center column">Something something something.This is a content section. Something something something.This is a content section. Something something something.This is a content section. Something something something.</p>
			</div>
		</div>
	</div>

	<div class="row smallpadding">
		<div class="medium-7 columns ">
			<div class="large-12 columns smallpadding">
				<h4 class="text-center column">Elton</h4>
				<p class="text-center column">Something something something.This is a content section. Something something something.This is a content section. Something something something.This is a content section. Something something something.</p>
			</div>
		</div>
		<div class="medium-5 columns">
			<img class="center" src="{% static "website/media/elton.jpg" %}">
		</div>
	</div>

	<div class="row smallpadding">
		<div class="medium-5 columns">
			<img class="center" src="{% static "website/media/reza.jpg" %}">
		</div>
		<div class="medium-7 columns ">
			<div class="large-12 columns smallpadding">
				<h4 class="text-center column">Reza</h4>
				<p class="text-center column">Something something something.This is a content section. Something something something.This is a content section. Something something something.This is a content section. Something something something.</p>
			</div>
		</div>
	</div>

	<div class="row smallpadding">
		<div class="medium-7 columns ">
			<div class="large-12 columns smallpadding">
				<h4 class="text-center column">Amy</h4>
				<p class="text-center column">Something something something.This is a content section. Something something something.This is a content section. Something something something.This is a content section. Something something something.</p>
			</div>
		</div>
		<div class="medium-5 columns">
			<img class="center" src="{% static "website/media/Amy.jpg" %}">
		</div>
	</div>

	<div class="row smallpadding">
		<div class="medium-5 columns">
			<img class="center" src="{% static "website/media/Zoe.jpg" %}">
		</div>
		<div class="medium-7 columns ">
			<div class="large-12 columns smallpadding">
				<h4 class="text-center column">Zoe</h4>
				<p class="text-center column">Something something something.This is a content section. Something something something.This is a content section. Something something something.This is a content section. Something something something.</p>
			</div>
		</div>
	</div>

</div>

{% endblock %}

intueriPLM/website/templates/contactus.html
{% extends "site_base.html" %}
{% load i18n %}

{% block title %}{% trans "Intueri" %}{% endblock %}
{% block content %}
<script>
$(".top-bar-section ul li:nth-child(4) a").addClass("active");
</script>

<div class="row">
	<div class="large-12 columns main-content-top">
		<div class="row">
			<h2>Contact Us</h2>
		</div>
	</div>
</div>

<div class="row main-content contactus">
	<div class="large-12 columns">
		<p>beta blah blah blahsldajfiow;ejfadls;kjf alwejf akls;fj ai;wej fl;as djlfkjas;flj lsadjf
		</p>
		<div class="row">
			<div class="small-6 columns">
				<h6>Your Name</h6>
				<input type="text" id="name" placeholder="">
				<h6>Your Email</h6>
				<input type="email" id="email" placeholder="">
				<h6>Subject</h6>
				<input type="text" id="subject" placeholder="">
				<h6>Your Message</h6>
				<textarea></textarea>
				<input type="submit" class="button small" value="Send"/>
			</div>
			<div class="small-4 right columns">
				<label>Email</label>
				<a href="mailto:info@intueri.com">info@intueri.com</a>
				<hr/>
				<label>Social Media</label>
				<p>
					<a href="#">Facebook</a> | 
					<a href="#">Twitter</a> | 
					<a href="#">Instagram</a>
				</p>
			</div>
		</div>
	</div>
</div><br>

{% endblock %}

intueriPLM/website/templates/index.html
{% extends "site_base.html" %}
{% load i18n %}

{% block title %}{% trans "Intueri" %}{% endblock %}
{% block content %}
<script>
$(".top-bar-section ul li:nth-child(1) a").addClass("active");
</script>

<div class="row main-content">
	<div class="large-12 columns">
		<div id="slider" class="slider slick-carousel single-item">
			<div>
				<img src="http://placehold.it/1000x400" alt="slide image">
			</div>
			<div>
				<img src="http://placehold.it/1000x400&text=Slide Image2" alt="slide image">
			</div>
		</div>
		<script>
		$('.single-item').slick({dots: true});
		</script>
	</div>
</div>

<div class="row main-content">
	<div class="large-12 center" style="max-width: 560px; max-height: 315px;">
		<div class="flex-video">
			<iframe width="560" height="315" src="https://www.youtube.com/embed/rYcvQqK5194" frameborder="0" allowfullscreen>
			</iframe>
		</div>
	</div>
</div>

<div class="row main-content">
	<div class="large-12 columns">
		<div class="row">
			<div class="small-6 columns nopadding">
				<div>
					<img src="http://placehold.it/500x485"/>
				</div>
				<div>
					<img class="nopadding" src="http://placehold.it/500x485"/>
				</div>
			</div>
			<div class="small-6 columns right nopadding">
				<div>
					<img src="http://placehold.it/500x970"/>
				</div>
			</div>
		</div>
		<div class="row">
			<div>
				<img class="center" src="http://placehold.it/1000x485"/>
			</div>
		</div>
	</div>
</div>

<div class="row main-content">
	<div class="large-12 columns">
		<div class="row">
			<h2>Some sort of text??</h2>
		</div>
	</div>
</div>

{% endblock %}

intueriPLM/website/templates/login.html
{% extends "PLM_base.html" %}
{% load i18n %}

{% block title %}{% trans "Intueri Login" %}{% endblock %}
{% block content %}
<form>
  <div class="row">
    <div class="small-8 columns">
      <div class="row">
        <div class="small-3 columns">
          <label for="right-label" class="right inline">Username</label>
        </div>
        <div class="small-9 columns">
          <input type="text" id="right-label" placeholder="Enter Email">
        </div>
      </div>
    </div>
  </div>
</form>
{% endblock %}

intueriPLM/website/templates/pricing.html
{% extends "site_base.html" %}
{% load i18n %}

{% block title %}{% trans "Intueri" %}{% endblock %}
{% block content %}
<script>
$(".top-bar-section ul li:nth-child(2) a").addClass("active");
</script>

<div class="row">
	<div class="large-12 columns main-content-top">
		<div class="row">
			<h2>Pricing</h2>
		</div>
	</div>
</div>

<div class="row main-content">	
	<div class="large-12 columns">
		<p>
			The most common pricing are listed here. Feel free to contact us for pricing details.
		</p>
	</div>
	<div class="large-4 columns">                      	
		<ul class="pricing-table">
			<li class="title">Standard</li>
			<li class="price">$99.99</li>
			<li class="description">An awesome description</li>
			<li class="bullet-item">5GB Storage</li>
			<li class="bullet-item">20 Users</li>
			<li class="cta-button"><a class="button" href="#">Buy Now</a></li>
		</ul>
	</div>
	<div class="large-4 columns">
		<ul class="pricing-table">
			<li class="title">Premium</li>
			<li class="price">$199.99</li>
			<li class="description">An awesome description</li>
			<li class="bullet-item">5 Database</li>
			<li class="bullet-item">10GB Storage</li>
			<li class="bullet-item">50 Users</li>
			<li class="cta-button"><a class="button" href="#">Buy Now</a></li>
		</ul>
	</div>
	<div class="large-4 columns">
		<ul class="pricing-table">
			<li class="title">Platinum</li>
			<li class="price">$299.99</li>
			<li class="description">An awesome description</li>
			<li class="bullet-item">Unlimited</li>
			<li class="bullet-item">50GB Storage</li>
			<li class="bullet-item">Unlimited</li>
			<li class="bullet-item">Analytics</li>
			<li class="cta-button"><a class="button" href="#">Buy Now</a></li>
		</ul>
	</div>
</div>

{% endblock %}

intueriPLM/website/templates/site_base.html
{% extends "base.html" %}
{% load i18n %}
{% load staticfiles %}

{% block title %}{% trans "Intueri" %}{% endblock %}
{% block css %}
<link href="{% static "base/css/base.css" %}" rel="stylesheet"/>
{% endblock %}

{% block base_body %}
{% block navigation %}
<header class="row main-navigation">
  <div class="large-12 columns">
    <nav class="top-bar" data-topbar role="navigation">
      <ul class="title-area">
        <li class="name logo">
          <a href="{% url 'website:index' %}">
            <img src="{% static "base/media/logo.png" %}">
          </a>
        </li>
        <li class="toggle-topbar menu-icon">
          <a href="#"><span>Menu</span></a>
        </li>
      </ul>
      <section class="top-bar-section">
        <ul class="right">
          <li><a href="{% url 'website:index' %}">Home</a></li>
          <li><a href="{% url 'website:pricing' %}">Pricing</a></li>
          <li><a href="{% url 'website:aboutus' %}">About Us</a></li>
          <li><a href="{% url 'website:contactus' %}">Contact Us</a></li>
          <li>
            <a href="{% url 'PLM:login' %}">Login/Register</a>
          </li>
        </ul>
      </section>
    </nav>
  </div>
</header>
{% endblock %}

{% block content %}

{% endblock %}

{% block footer %}
{% include "_footer.html" %}
{% endblock %}

{% endblock %}